"""
Detection Engineering Agent
============================
Generates detection rule DRAFTS — never auto-deploys rules.
Output types: Sigma YAML | WAF rule | SIEM query | EDR hunt | Cloud query
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
import uuid


class DetectionEngineeringAgent:
    """
    Generates defensive detection rule drafts from findings or actor clusters.
    All rules require human review before deployment.
    """

    def from_finding(self, finding: Dict[str, Any], tenant_id: str) -> List[Dict[str, Any]]:
        """Generate detection drafts from an offensive finding."""
        drafts = []
        title = finding.get("title", "")
        risk = finding.get("risk_level", "medium")
        description = finding.get("description", "")

        # Generate Sigma rule
        drafts.append(self._sigma_draft(title, description, risk, tenant_id))

        # Generate SIEM query
        drafts.append(self._siem_query_draft(title, description, tenant_id))

        return drafts

    def from_cluster(self, cluster: Dict[str, Any], tenant_id: str) -> List[Dict[str, Any]]:
        """Generate detection drafts from an actor cluster."""
        drafts = []
        cluster_id = cluster.get("cluster_id", "UNKNOWN")
        fingerprint = cluster.get("fingerprint", {})
        asns = fingerprint.get("asn_pattern", [])
        ja3s = fingerprint.get("ja3_fingerprints", [])

        # Sigma rule for cluster behavior
        drafts.append({
            "id": str(uuid.uuid4()),
            "tenant_id": tenant_id,
            "title": f"Behavioral Cluster {cluster_id} — Suspicious Activity Pattern",
            "rule_type": "sigma",
            "status": "draft",
            "content": self._render_sigma_cluster(cluster_id, asns, ja3s),
            "description": (
                f"Detects behavioral pattern matching actor cluster {cluster_id}. "
                "Confidence: {:.0%}. REVIEW BEFORE DEPLOYMENT.".format(
                    cluster.get("confidence", 0.0)
                )
            ),
            "cluster_id": cluster_id,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        })

        # WAF rule if HTTP pattern observed
        if fingerprint.get("path_probing_sequence"):
            drafts.append(self._waf_rule_draft(cluster_id, fingerprint, tenant_id))

        return drafts

    def _sigma_draft(
        self, title: str, description: str, risk: str, tenant_id: str
    ) -> Dict[str, Any]:
        sigma_level = {
            "critical": "critical",
            "high": "high",
            "medium": "medium",
            "low": "low",
        }.get(risk, "medium")

        content = f"""# SIGMA RULE DRAFT — REVIEW REQUIRED BEFORE DEPLOYMENT
title: '{title}'
id: {uuid.uuid4()}
status: experimental
description: |
  {description}
  Generated by AegisTwin Detection Engineering Agent. Requires analyst review.
author: AegisTwin
date: {datetime.now(timezone.utc).strftime('%Y/%m/%d')}
tags:
  - aegistwin.draft
  - needs_review
logsource:
  category: webserver
  product: generic
detection:
  selection:
    # TODO: Refine selectors based on your SIEM log schema
    cs-uri-stem|contains:
      - '/admin'
      - '/api/v1/users'
      - '/.env'
  condition: selection
level: {sigma_level}
falsepositives:
  - Authorized penetration testing
  - Internal security scanning
"""
        return {
            "id": str(uuid.uuid4()),
            "tenant_id": tenant_id,
            "title": f"[DRAFT] {title}",
            "rule_type": "sigma",
            "status": "draft",
            "content": content,
            "description": f"Sigma rule draft for: {title}",
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    def _siem_query_draft(
        self, title: str, description: str, tenant_id: str
    ) -> Dict[str, Any]:
        content = f"""-- SIEM QUERY DRAFT (Splunk SPL) — REVIEW REQUIRED
-- Finding: {title}
-- Generated: {datetime.now(timezone.utc).isoformat()}

index=web_access
| where status IN (401, 403, 404)
| stats count by src_ip, uri_path
| where count > 10
| sort - count
| eval risk="REVIEW REQUIRED"
-- TODO: Tune count threshold and path filters for your environment
"""
        return {
            "id": str(uuid.uuid4()),
            "tenant_id": tenant_id,
            "title": f"[DRAFT] SIEM Hunt — {title}",
            "rule_type": "siem_query",
            "status": "draft",
            "content": content,
            "description": f"SIEM hunting query for: {title}",
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    def _waf_rule_draft(
        self, cluster_id: str, fingerprint: Dict[str, Any], tenant_id: str
    ) -> Dict[str, Any]:
        ips = fingerprint.get("source_ips", [])
        paths = fingerprint.get("path_probing_sequence", [])[:5]
        ip_list = " ".join([f'"{ip}"' for ip in ips[:10]])

        content = f"""# WAF RULE DRAFT — REVIEW REQUIRED BEFORE DEPLOYMENT
# Cluster: {cluster_id}
# Generated: {datetime.now(timezone.utc).isoformat()}

# ModSecurity style (adapt for your WAF)
SecRule REMOTE_ADDR "@ipMatch {ip_list}" \\
  "id:900001,phase:1,deny,status:403,\\
   msg:'AegisTwin — Known malicious IP from cluster {cluster_id}',\\
   log,auditlog"

# Block observed probe paths
SecRule REQUEST_URI "@beginsWith {paths[0] if paths else '/admin'}" \\
  "id:900002,phase:1,deny,status:403,\\
   msg:'AegisTwin — Known probe path from cluster {cluster_id}',\\
   log,auditlog"

# NOTE: Test in LOG-ONLY mode before blocking.
# Review false positive rate over 24h before switching to DENY mode.
"""
        return {
            "id": str(uuid.uuid4()),
            "tenant_id": tenant_id,
            "title": f"[DRAFT] WAF Block Rule — Cluster {cluster_id}",
            "rule_type": "waf",
            "status": "draft",
            "content": content,
            "description": f"WAF rule draft targeting actor cluster {cluster_id}",
            "cluster_id": cluster_id,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    def _render_sigma_cluster(
        self, cluster_id: str, asns: List[str], ja3s: List[str]
    ) -> str:
        asn_list = "\n      - ".join(asns) if asns else "# No ASNs identified"
        ja3_list = "\n      - ".join(ja3s) if ja3s else "# No JA3 fingerprints"

        return f"""# SIGMA RULE DRAFT — REVIEW REQUIRED
title: 'Behavioral Cluster {cluster_id} — Suspicious Multi-Source Activity'
id: {uuid.uuid4()}
status: experimental
description: |
  Detects activity matching fingerprint of actor cluster {cluster_id}.
  Requires analyst review before deployment.
author: AegisTwin Defensive Hunter
date: {datetime.now(timezone.utc).strftime('%Y/%m/%d')}
tags:
  - aegistwin.cluster
  - needs_review
logsource:
  category: proxy
  product: generic
detection:
  selection_asn:
    # Source ASN matching — adapt to your log field names
    src_asn:
      - {asn_list}
  selection_ja3:
    tls.ja3:
      - {ja3_list}
  condition: selection_asn or selection_ja3
level: high
falsepositives:
  - Authorized penetration testing
  - Cloud provider scanning
"""
