// @ts-nocheck
import { useState } from 'react';
import { useEffect, useState } from 'react';
import { api } from '../api/client';

export default function DetectionDrafts() {
  const [drafts, setDrafts] = useState<any[]>([]);
  useEffect(() => { api.getDetectionDrafts().then(setDrafts).catch(console.error); }, []);
  const [selected, setSelected] = useState(mockDetectionDrafts[0]);
  return (
    <div>
      <div className="page-header">
        <div className="page-header-info">
          <h1>Detection Engineering Drafts</h1>
          <p>AI-generated detection rules — requires human review before deployment</p>
        </div>
        <span className="badge badge-medium">{drafts.length} Drafts</span>
      </div>

      <div className="alert alert-warning" style={{ marginBottom: 20 }}>
        ⚠️ These are DRAFT rules generated by AegisTwin. They must be reviewed, tested in
        log-only mode, and approved before deployment to production systems.
      </div>

      <div className="grid-2">
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {drafts.map(d => (
            <div key={d.id} className="card" onClick={() => setSelected(d)}
              style={{ cursor: 'pointer', borderColor: selected.id === d.id ? 'var(--accent-cyan)' : 'var(--border)' }}>
              <div style={{ display: 'flex', gap: 8, marginBottom: 8 }}>
                <span className="badge badge-medium">{d.rule_type.toUpperCase()}</span>
                <span className="badge badge-info">{d.status}</span>
              </div>
              <div style={{ fontWeight: 600, color: 'var(--text-primary)', fontSize: '0.875rem' }}>
                {d.title}
              </div>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 4 }}>
                {d.description}
              </div>
            </div>
          ))}
        </div>

        <div className="card">
          <div className="card-header">
            <span className="card-title">Rule Content</span>
            <button className="btn btn-secondary" style={{ fontSize: '0.72rem' }}>Copy</button>
          </div>
          <div className="code-block">{selected.content}</div>
          <div style={{ marginTop: 16, display: 'flex', gap: 8 }}>
            <button className="btn btn-secondary">Request Review</button>
            <button className="btn btn-secondary" style={{ color: 'var(--risk-low)' }}>
              Mark as Reviewed
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
