"""
Remediation Agent
==================
Generates structured remediation tickets (Jira/GitHub format),
owner suggestions, priority recommendations, and retest plans.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
import uuid


PRIORITY_MAP = {
    "critical": "P0",
    "high": "P1",
    "medium": "P2",
    "low": "P3",
    "informational": "P4",
}

OWNER_MAP = {
    "web_app": "Application Security Team",
    "api": "Platform Engineering",
    "repository": "DevSecOps Team",
    "cloud_account": "Cloud Infrastructure Team",
    "identity_provider": "Identity & Access Management Team",
    "database": "Data Engineering Team",
    "network_device": "Network Operations",
}


class RemediationAgent:
    """
    Generates Jira and GitHub issue JSON payloads from findings.
    Never modifies production systems — output is read-only structured data.
    """

    def from_finding(
        self,
        finding: Dict[str, Any],
        tenant_id: str,
        asset_type: Optional[str] = None,
    ) -> List[Dict[str, Any]]:
        """Generate both a Jira and a GitHub ticket from a finding."""
        tickets = []
        tickets.append(self._jira_ticket(finding, tenant_id, asset_type))
        tickets.append(self._github_issue(finding, tenant_id, asset_type))
        return tickets

    def _jira_ticket(
        self,
        finding: Dict[str, Any],
        tenant_id: str,
        asset_type: Optional[str],
    ) -> Dict[str, Any]:
        risk = finding.get("risk_level", "medium")
        priority = PRIORITY_MAP.get(risk, "P2")
        owner_team = OWNER_MAP.get(asset_type or "web_app", "Security Team")

        return {
            "id": str(uuid.uuid4()),
            "tenant_id": tenant_id,
            "finding_id": finding.get("id"),
            "title": f"[SECURITY] {finding.get('title', 'Security Finding')}",
            "description": self._jira_description(finding),
            "priority": risk,
            "suggested_owner": owner_team,
            "ticket_type": "jira",
            "ticket_payload": {
                "project": {"key": "SEC"},
                "summary": f"[{risk.upper()}] {finding.get('title', '')}",
                "description": self._jira_description(finding),
                "issuetype": {"name": "Security Bug"},
                "priority": {"name": priority},
                "labels": ["security", "aegistwin", risk],
                "assignee": {"displayName": owner_team},
                "customfield_risk_score": finding.get("risk_score"),
                "customfield_cve": finding.get("cve_ids", []),
            },
            "retest_plan": finding.get("retest_plan"),
            "status": "open",
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    def _github_issue(
        self,
        finding: Dict[str, Any],
        tenant_id: str,
        asset_type: Optional[str],
    ) -> Dict[str, Any]:
        risk = finding.get("risk_level", "medium")
        owner_team = OWNER_MAP.get(asset_type or "web_app", "Security Team")

        return {
            "id": str(uuid.uuid4()),
            "tenant_id": tenant_id,
            "finding_id": finding.get("id"),
            "title": f"[SECURITY] {finding.get('title', 'Security Finding')}",
            "description": self._github_body(finding),
            "priority": risk,
            "suggested_owner": owner_team,
            "ticket_type": "github",
            "ticket_payload": {
                "title": f"[SECURITY/{risk.upper()}] {finding.get('title', '')}",
                "body": self._github_body(finding),
                "labels": ["security", risk, "needs-fix"],
                "assignees": [],  # To be filled by owner team
                "milestone": None,
            },
            "retest_plan": finding.get("retest_plan"),
            "status": "open",
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    def _jira_description(self, finding: Dict[str, Any]) -> str:
        return f"""h2. Security Finding

*Severity:* {finding.get("risk_level", "").upper()}
*Risk Score:* {finding.get("risk_score", "N/A")}
*CVE IDs:* {", ".join(finding.get("cve_ids") or ["None"])}

h3. Description
{finding.get("description", "No description provided.")}

h3. Evidence
{chr(10).join(f"* {e}" for e in (finding.get("evidence") or ["No evidence attached"]))}

h3. Recommended Fix
{finding.get("recommended_fix", "No fix specified.")}

h3. Retest Plan
{finding.get("retest_plan", "No retest plan specified.")}

----
_Generated by AegisTwin at {datetime.now(timezone.utc).isoformat()}_
"""

    def _github_body(self, finding: Dict[str, Any]) -> str:
        evidence = "\n".join(
            f"- {e}" for e in (finding.get("evidence") or ["No evidence attached"])
        )
        return f"""## 🚨 Security Finding

| Field | Value |
|---|---|
| **Severity** | `{finding.get("risk_level", "").upper()}` |
| **Risk Score** | `{finding.get("risk_score", "N/A")}` |
| **CVE IDs** | `{", ".join(finding.get("cve_ids") or ["None"])}` |

### Description
{finding.get("description", "No description provided.")}

### Evidence
{evidence}

### Recommended Fix
{finding.get("recommended_fix", "No fix specified.")}

### Retest Plan
{finding.get("retest_plan", "No retest plan specified.")}

---
_Generated by AegisTwin · {datetime.now(timezone.utc).isoformat()}_
"""


# Singleton
remediation_agent = RemediationAgent()
